flike/kingshard

README.md

Hi,
I have fixed couple of errors in the README.md.

Fixed few grammatical errors in README.md.

---

doc/KingDoc/kingshard_quick_try.md

Signed-off-by: Gavin Tao <gavin.tao17@gmail.com>

add quick try docment

---

proxy/router/router.go

Signed-off-by: Gavin Tao <gavin.tao17@gmail.com>

bugfix[use database command not work! #15]

---

backend/backend_conn.go

" time.Now().Unix()"  change to "time.Now().UnixNano()"

fixed Ping method trigger condition

---

mysql/util.go
mysql/util_test.go

seed must be in the range of ascii, except ascii(0)

fixed handshake auth for jdbc:

---

README.md

modify doc

---

sqlparser/analyzer.go

bugfix[trim \`database\`.\`table\` name]

bugfix[trim `database`.`table` name]

---

proxy/server/conn.go

server: fixed bug[Invalid conditions]

---

backend/db.go
backend/node.go
config/config.go
core/errors/errors.go
etc/ks.yaml
proxy/server/conn_admin.go
proxy/server/server_test.go

limit the max connections count to mysql

limit the max connections count to mysql

---

proxy/server/conn_query.go

fix bug issue64

---

backend/db.go
backend/node.go
proxy/server/server.go

separate down node manually from down node automatically

---

doc/KingDoc/how_to_use_kingshard_EN.md
doc/KingDoc/kingshard_install_document.md
etc/ks.yaml
etc/unshard.yaml
proxy/server/conn.go

bugfix issue #78 [show databases error]

---

backend/backend_conn.go
backend/backend_conn_test.go
proxy/server/conn_query.go
proxy/server/conn_set.go
proxy/server/conn_tx.go

1.fix issue https://github.com/flike/kingshard/issues/92
2.remove write lock of ClientConn.txConns

Bugfix issue 92

---

proxy/server/conn_query.go

bugfix issue #92 [set autocommit=x, poor tokens split]

---

core/errors/errors.go
proxy/router/router.go

force insert replace specfiy columns

---

proxy/server/conn_preshard.go
proxy/server/conn_query.go

code refactor

---

README_ZH.md
config/config.go
doc/KingDoc/how_to_use_kingshard.md
doc/KingDoc/how_to_use_kingshard_EN.md
doc/KingDoc/kingshard_install_document.md
doc/KingDoc/sql_blacklist_introduce.md
etc/ks.yaml
etc/unshard.yaml
mysql/sql_fingerprint.go
mysql/sql_fingerprint_test.go
proxy/server/conn_preshard.go
proxy/server/server.go

Feature blacklist sql

---

doc/KingDoc/admin_command_introduce.md
proxy/server/conn.go
proxy/server/conn_admin.go
proxy/server/conn_query.go
proxy/server/counter.go
proxy/server/server.go

kingshard runtime sql count.
1.client connections
2.client qps
3.slow log sql
4.error log sql

feature sql counter

---

config/config.go
proxy/server/conn_admin.go
proxy/server/server.go

1.log on-off switch
2.change slow log time
3.add/del allow_ip
4.add/del black sql
5.save config

config reload draft

---

proxy/server/conn.go
proxy/server/conn_admin.go
proxy/server/conn_preshard.go
proxy/server/conn_query.go
proxy/server/server.go

optimization: remove lock of proxy server

remove lock of proxy server

---

proxy/server/conn.go

deal with issue https://github.com/flike/kingshard/issues/156

---

proxy/server/conn.go

issue:https://github.com/flike/kingshard/issues/166

mysql close connection client should be told

---

backend/backend_conn.go

see more: https://github.com/flike/kingshard/issues/185

refix bug #185:

---

proxy/server/conn_preshard.go
proxy/server/conn_set.go

Deal with issue #188     
start transaction use autocommit support @@session, @@ prefix
set character_set* support @@, @@session prefix

autocommit, character_set* support @@ && @@session

---

doc/KingDoc/kingshard_date_sharding.md

时间分表文档笔误修改

---

.gitignore

ignore .vscode/ which is created by vscode editor

git ignore vs code directory

---

core/hack/version.go
doc/KingDoc/admin_command_introduce.md
doc/KingDoc/command_help
doc/KingDoc/function_FAQ.md
doc/KingDoc/how_to_use_kingshard_EN.md
proxy/server/conn_admin.go
proxy/server/server.go

1.support lvs/keepalived status check
2.upgrade related admin docs and FAQ

support lvs/keepalived status check

---

proxy/router/planbuilder.go
proxy/router/router.go
proxy/router/router_test.go

Those set of change is for feature in optimize, it looks better and resolved some potential issue.

fix #183, feature in optimize, make the code clean and added more test cases for other complicated scenario 

---

core/errors/errors.go
proxy/server/server.go

1.fix bug of add/del black sqls

fix bug of add/del black sqls

---

backend/node.go
proxy/server/server.go

1.fix bug of save config file
2.strengthen duplicate check of add slave

fix bug of save config file

---

backend/db.go
backend/node.go
proxy/server/conn_admin.go

1.check remove mysql server alive
2.mark ping time of each mysql instance

optimize check alive of node

---

backend/node.go
config/config.go
core/hack/version.go
etc/ks.yaml
etc/unshard.yaml
proxy/server/server.go

1.use default user/password in ups instead of node config
2.upgrade config file

use default user/password in ups instead of node config

---

doc/KingDoc/kingshard_date_sharding.md

Fix typo of supporting date and time types.

[Doc] Fix typo of supporting date and time types

---

backend/backend_conn.go
config/config.go
config/config_test.go
core/hack/version.go
doc/KingDoc/how_to_use_kingshard.md
doc/KingDoc/how_to_use_kingshard_EN.md
doc/KingDoc/kingshard_date_sharding.md
doc/KingDoc/kingshard_install_document.md
doc/KingDoc/kingshard_quick_try.md
doc/KingDoc/kingshard_sharding_introduce.md
etc/ks.yaml
etc/unshard.yaml
proxy/router/router.go
proxy/router/router_test.go
proxy/server/conn.go
proxy/server/conn_admin.go
proxy/server/conn_preshard.go
proxy/server/conn_query.go
proxy/server/conn_select.go
proxy/server/conn_stmt.go
proxy/server/conn_test.go
proxy/server/conn_use.go
proxy/server/server.go
proxy/server/server_test.go
sqlparser/analyzer.go
web/api.go

support multi database for sharding table

Feature multi schema

---

doc/KingDoc/kingshard_support_sql.md
mysql/const.go
proxy/router/router.go
proxy/server/conn_preshard.go
proxy/server/conn_query.go
sqlparser/ast.go
sqlparser/sql.go
sqlparser/sql.y
sqlparser/token.go

在分表上可使用`truncate [table] tbl_name`语法进行操作。

support truncate table on shard table #290

---

proxy/server/conn_resultset.go

修复带函数并且有sharding、group by及order by的情况下，返回的数据未按照order进行排序的问题

修复带函数并且有sharding、group by及order by的情况下，返回的数据未按照order进行排序的问题

---

monitor/prometheus.go

修复map可能存在的race

---

backend/db.go
core/hack/version.go

修复tryReuse时可能出现的无法连接问题

---

doc/KingDoc/how_to_use_kingshard.md
doc/KingDoc/kingshard_install_document.md

change doc go-1.6 to go-latest

---

README_ZH.md

Fix typo in README_ZH.md

---

doc/KingDoc/kingshard_sharding_introduce.md

fix sharding name typo error

---

Dockerfile

支持Docker镜像构建

---

monitor/prometheus.go

fix: 1. 修复监控节点数据被覆盖问题 2. 新增节点没有动态监控问题

fix: 1. 修复监控节点数据被覆盖问题 2. 新增节点没有动态监控问题

---

backend/backend_conn.go

MySQL Server存在一个SERVER_STATUS的[bug](https://bugs.mysql.com/bug.php?id=66884)。
如果根据Response的响应，`SERVER_STATUS_AUTOCOMMIT`这一位永远为1，kingshard也就不会去[设置conn](https://github.com/flike/kingshard/blob/master/backend/backend_conn.go#L116)的autocommit。

fix: adapt for a mysql's Server Status bug
